### ISSUE TITLE
Configuring GF 

### ISSUE THREAD

**Issue by juicyarts** [burnettk/vim-angular#18]
This is no issue but a feature which would be very useful.
Currently "gf" tries to find patterns like "*-service.js". 
It would be great if one could overwrite this behaviour with something like "*.service.js" as modern frameworks like mean use this kind of file naming structure. 
Would be really helpful for my workflow. is there an option to configure this?

**Comment by burnettk** [comment]
can you provide more details about your file and class name conventions? if i generate a mean app using http://meanjs.org/generator.html, i end up with a service class called "ArticlesService" defined in a file named "./mean/modules/articles/client/services/articles.client.service.js," so i would expect to be able to hit gf when the cursor was on ArticlesService and be taken to articles.client.service.js (this does not work currently, because of the dots and because of the "client" in the middle of the filename. is this your exact use case, or would your ArticlesService be in a file called articles.service.js (which also doesn't work currently, because of the dot)? do you have any classes composed of multiple words (like SuperAwesomeThingService), and are they in files like super.awesome.thing.service.js? I don't want to add a feature that doesn't work for you (feel free to add the unit tests in [spec/gf_definition_spec.rb](spec/gf_definition_spec.rb)).

**Comment by quaqua** [comment]
+1

My structure (I'm using yeoman generator-gulp-angular)

```
my_name.service.js -> MyName || myName || MyNameService || myNameService
my_model.factory.js -> MyModel
```

That basically would require to try for files with `.service.js .factory.js .provider.js .directive.js component.js` and so on.

**Comment by natchiketa** [comment]
I've created a PR that addresses this. I think the naming convention described here is the same as described in the Angular style guides by [John Poppa](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#feature-file-names) and [Todd Motto](https://github.com/toddmotto/angular-styleguide#scalable-file-structure).

**Comment by burnettk** [comment]
bravo, @natchiketa , nice work. merged!
